In [94]:
import numpy as np

In [95]:
pose = [[290, 85], [294, 94], [292, 94], [288, 105], [284, 108], [296, 94], [300, 105], [293, 113], [294, 114], [293, 129], [299, 147], [300, 115], [297, 129], [303, 149], [288, 84], [292, 85], [-1, -1], [293, 85]]

In [96]:
np.reshape(pose, 36)

array([290,  85, 294,  94, 292,  94, 288, 105, 284, 108, 296,  94, 300,
       105, 293, 113, 294, 114, 293, 129, 299, 147, 300, 115, 297, 129,
       303, 149, 288,  84, 292,  85,  -1,  -1, 293,  85])

In [105]:
dat = np.loadtxt("pose_table.csv", delimiter=",")
dat

array([[295.,  93., 298., 100., 291., 102., 286., 113., 288., 120., 305.,
         98., 313., 110., 307., 124., 293., 124., 293., 139., 294., 158.,
        304., 123., 304., 140., 304., 157., 294.,  90., 298.,  89., 293.,
         93., 302.,  90.],
       [291., 108., 292., 120., 282., 123., 281., 139., 280., 152., 303.,
        119., 307., 138., 312., 152., 289., 151., 291., 172., 293., 191.,
        302., 150., 304., 171., 305., 190., 286., 107., 292., 107., 283.,
        108., 294., 107.],
       [252., 160., 261., 169., 243., 170., 239., 193., 247., 204., 276.,
        168., 283., 192., 271., 204., 259., 210., 261., 229., 266., 246.,
        274., 205., 282., 225., 283., 244., 249., 159., 253., 157.,  -1.,
         -1., 262., 149.],
       [233., 245., 246., 245., 224., 246., 219., 279., 223., 300., 269.,
        244., 281., 274., 264., 292., 242., 290., 229., 310., 252., 325.,
        267., 288., 274., 303., 282., 320., 230., 243., 239., 242.,  -1.,
         -1., 249., 232.],
    

In [102]:
dat2 = np.arange(20).reshape((4,5))
dat2[1][1] = -1
dat2[0][3] = dat2[1][3] = dat2[2][3] = -1
dat2

array([[ 0,  1,  2, -1,  4],
       [ 5, -1,  7, -1,  9],
       [10, 11, 12, -1, 14],
       [15, 16, 17, 18, 19]])

In [78]:
dat = dat2
loss_index_y, loss_index_x = np.where(dat==-1)
for y,x in zip(loss_index_y, loss_index_x):
    y0 = y1 = y
    range_count = 0
    while True:
        range_count += 1
        y0 -= 1
        try:
            before_val = dat[y0,x]
        except IndexError as err:
            print(err)
            break
        if before_val > 0:
            break
    
    while True:
        range_count += 1
        y1 += 1
        try:
            after_val = dat[y1,x]
        except IndexError as err:
            print(err)
            break
        if after_val > 0:
            break
    
    t = y1 - y0 - 1
    for i in range(t):
        print("result", y0 *(i+1) + y1 * (t-i))
        dat[y][x] = 
    
    
    
    print(range_count)
    print(y0, y1)
    print(before_val, after_val)

print(dat)

SyntaxError: invalid syntax (<ipython-input-78-6e9263041d02>, line 31)

In [111]:
#dat = dat2.copy()

#[i[0] for i in np.where(dat==-1)]

while True:
    nan_index = np.where(dat==-1)
    if np.shape(nan_index) == (2,0):
        break
    loss_index = [i[0] for i in nan_index]
    
    y0 = y1 = loss_index[0]
    x = loss_index[1]
    range_count = 0
    while True:
        range_count += 1
        y0 -= 1
        try:
            before_val = dat[y0,x]
        except IndexError as err:
            print(err)
            dat[y1+1][x] = dat[y][x]
            break
        if before_val > 0:
            break
    
    while True:
        range_count += 1
        y1 += 1
        try:
            after_val = dat[y1,x]
        except IndexError as err:
            print(err)
            dat[y1-1][x] = dat[y][x]
            break
        if after_val > 0:
            break
            
    #t = y1 - y0 - 1
    for i in range(y0+1, y1):
        try:
            print("orig_val", dat[i][x])
            print("y0 i y1 range_count i", y0, i, y1, range_count, i)
            print("y0 i y1 range_count i", dat[y0][x] ,(range_count-i) ,dat[y1][x] ,(i))
            print("result", dat[y0][x] *(range_count-i-1) + dat[y1][x] * (i+1))
        #try:
            dat[i][x] = (dat[y0][x] *(range_count-i) + dat[y1][x] * i) \
                / range_count
        except IndexError as err:
            print(dat)
            np.savetxt("calibrate_test.csv", dat, delimiter=",")
        
    print("-------------------")
    
    #dat[loss_index[0]][loss_index[1]] = 1

print("org", dat2)
print("dat", dat)

('org', array([[ 0,  1,  2, -1,  4],
       [ 5, -1,  7, -1,  9],
       [10, 11, 12, -1, 14],
       [15, 16, 17, 18, 19]]))
('dat', array([[ 295.        ,   93.        ,  298.        ,  100.        ,
         291.        ,  102.        ,  286.        ,  113.        ,
         288.        ,  120.        ,  305.        ,   98.        ,
         313.        ,  110.        ,  307.        ,  124.        ,
         293.        ,  124.        ,  293.        ,  139.        ,
         294.        ,  158.        ,  304.        ,  123.        ,
         304.        ,  140.        ,  304.        ,  157.        ,
         294.        ,   90.        ,  298.        ,   89.        ,
         293.        ,   93.        ,  302.        ,   90.        ],
       [ 291.        ,  108.        ,  292.        ,  120.        ,
         282.        ,  123.        ,  281.        ,  139.        ,
         280.        ,  152.        ,  303.        ,  119.        ,
         307.        ,  138.        ,  312.      

In [63]:
np.shape(np.where(np.arange(20).reshape(4,5)==-1))
#len(np.where(dat==-1))

(2, 0)

In [107]:
np.shape(dat)

(23, 36)