In [39]:
import numpy as np

In [40]:
pose = [[290, 85], [294, 94], [292, 94], [288, 105], [284, 108], [296, 94], [300, 105], [293, 113], [294, 114], [293, 129], [299, 147], [300, 115], [297, 129], [303, 149], [288, 84], [292, 85], [-1, -1], [293, 85]]

In [41]:
np.reshape(pose, 36)

array([290,  85, 294,  94, 292,  94, 288, 105, 284, 108, 296,  94, 300,
       105, 293, 113, 294, 114, 293, 129, 299, 147, 300, 115, 297, 129,
       303, 149, 288,  84, 292,  85,  -1,  -1, 293,  85])

In [42]:
dat = np.loadtxt("pose_table.csv", delimiter=",")
dat

array([[295.,  93., 298., 100., 291., 102., 286., 113., 288., 120., 305.,
         98., 313., 110., 307., 124., 293., 124., 293., 139., 294., 158.,
        304., 123., 304., 140., 304., 157., 294.,  90., 298.,  89., 293.,
         93., 302.,  90.],
       [291., 108., 292., 120., 282., 123., 281., 139., 280., 152., 303.,
        119., 307., 138., 312., 152., 289., 151., 291., 172., 293., 191.,
        302., 150., 304., 171., 305., 190., 286., 107., 292., 107., 283.,
        108., 294., 107.],
       [252., 160., 261., 169., 243., 170., 239., 193., 247., 204., 276.,
        168., 283., 192., 271., 204., 259., 210., 261., 229., 266., 246.,
        274., 205., 282., 225., 283., 244., 249., 159., 253., 157.,  -1.,
         -1., 262., 149.],
       [233., 245., 246., 245., 224., 246., 219., 279., 223., 300., 269.,
        244., 281., 274., 264., 292., 242., 290., 229., 310., 252., 325.,
        267., 288., 274., 303., 282., 320., 230., 243., 239., 242.,  -1.,
         -1., 249., 232.],
    

In [47]:
dat2 = np.arange(20).reshape((4,5))
dat2[1][1] = -1
dat2[1][3] = dat2[2][3] = -1
dat2

array([[ 0,  1,  2,  3,  4],
       [ 5, -1,  7, -1,  9],
       [10, 11, 12, -1, 14],
       [15, 16, 17, 18, 19]])

In [50]:
dat = dat2
loss_index_y, loss_index_x = np.where(dat==-1)
for y,x in zip(loss_index_y, loss_index_x):
    y0 = y1 = y
    range_count = 0
    while True:
        range_count += 1
        y0 -= 1
        try:
            before_val = dat[y0,x]
        except IndexError as err:
            print(err)
            break
        if before_val > 0:
            break
    
    while True:
        range_count += 1
        y1 += 1
        try:
            after_val = dat[y1,x]
        except IndexError as err:
            print(err)
            break
        if after_val > 0:
            break
    
    t = y1 - y0 - 1
    for i in range(t):
        print("result", y0 *(i+1) + y1 * (t-i))
        dat[y][x] = 
    
    
    
    print(range_count)
    print(y0, y1)
    print(before_val, after_val)

print(dat)

('result', 2)
2
(0, 2)
(1, 11)
('result', 6)
('result', 3)
3
(0, 3)
(3, 18)
('result', 6)
('result', 3)
3
(0, 3)
(3, 18)
[[ 0  1  2  3  4]
 [ 5 -1  7 -1  9]
 [10 11 12 -1 14]
 [15 16 17 18 19]]


In [ ]:
dat = dat2


# while True:
#    loss_index_y, loss_index_x = np.where(dat==-1)
    